export enum FloorType {
  Ground = 'Ground',
  First = 'First',
  Second = 'Second',
  Third = 'Third',
  Fourth = 'Fourth',
  Fifth = 'Fifth',
}

export enum BusinessType {
  INDIVIDUAL = 'INDIVIDUAL',
  SOLE_PROPRIETORSHIP = 'SOLE_PROPRIETORSHIP',
  PARTNERSHIP = 'PARTNERSHIP',
  LIMITED_LIABILITY_COMPANY = 'LIMITED_LIABILITY_COMPANY',
  COOPERATIVE = 'COOPERATIVE',
  OTHER = 'OTHER',
}

export enum ExpectedMonthlySales {
  UNDER_1000 = 'UNDER_1000',
  ONE_TO_FIVE_THOUSAND = 'ONE_TO_FIVE_THOUSAND',
  FIVE_TO_TEN_THOUSAND = 'FIVE_TO_TEN_THOUSAND',
  TEN_TO_FIFTY_THOUSAND = 'TEN_TO_FIFTY_THOUSAND',
  FIFTY_TO_HUNDRED_THOUSAND = 'FIFTY_TO_HUNDRED_THOUSAND',
  OVER_HUNDRED_THOUSAND = 'OVER_HUNDRED_THOUSAND',
}
