export const VENDOR_APPLICATION_STATUS = {
  PENDING: 'PENDING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  DOCUMENTS_REQUESTED: 'DOCUMENTS_REQUESTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
} as const;

export const VENDOR_BUSINESS_TYPES = {
  INDIVIDUAL: 'INDIVIDUAL',
  SOLE_PROPRIETORSHIP: 'SOLE_PROPRIETORSHIP',
  PARTNERSHIP: 'PARTNERSHIP',
  LIMITED_LIABILITY_COMPANY: 'LIMITED_LIABILITY_COMPANY',
  CORPORATION: 'CORPORATION',
  COOPERATIVE: 'COOPERATIVE',
  OTHER: 'OTHER',
} as const;

export type VendorApplicationStatus =
  (typeof VENDOR_APPLICATION_STATUS)[keyof typeof VENDOR_APPLICATION_STATUS];
export type VendorBusinessType =
  (typeof VENDOR_BUSINESS_TYPES)[keyof typeof VENDOR_BUSINESS_TYPES];
