#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep -E 'package(-lock)?\.json'; then
  echo "Dependencies changed, running npm install..."
  npm install
fi 